export const krt = [
    {
        "id": 1,
        "kadastr": "77:17:0150309:1238",
        "culture": "0",
        "zu_protect": "Не расположен",
        "expert": "Иванов А.А.",
        "zu_culture": "Не расположен",
        "comment": "Нет",
        "oks": "Нет",
        "date": "18.11.2021",
    },
    {
        "id": 2,
        "kadastr": "77:17:0150309:1238",
        "culture": "0",
        "zu_protect": "Не расположен",
        "expert": "Петров А.А.",
        "zu_culture": "Не расположен",
        "comment": "Нет",
        "oks": "Нет",
        "date": "20.11.2021",
    },
    {
        "id": 3,
        "kadastr": "77:17:0150309:1238",
        "culture": "0",
        "zu_protect": "Не расположен",
        "expert": "Сидоров А.А.",
        "zu_culture": "Не расположен",
        "comment": "Нет",
        "oks": "Нет",
        "date": "22.11.2021",
    }
]